"""
Generate src/data/articles.ts from the categorized news metadata.

Phase 2 deliverable — populates title, slug, date, excerpt, category,
heroImage. Body is left as an empty array; Phase 3 fills bodies.

Run from the website folder:
    python3 tools/generate_articles_ts.py
"""

import json
import re
from html import unescape
from pathlib import Path

ROOT = Path(__file__).parent.parent
METADATA = ROOT / "tools" / "news-metadata.json"
CATEGORIZED = ROOT / "tools" / "news-categorized.json"
HERO_DIR = ROOT / "public" / "images" / "articles"
OUT = ROOT / "src" / "data" / "articles.ts"

# Tiny placeholder fallback images (9 KB ones) — flag for user review
PLACEHOLDER_SLUGS_FILE = ROOT / "tools" / "_placeholder-heroes.txt"

CATEGORY_META = [
    {
        "slug": "wines",
        "label": "Wines",
        "blurb": "New releases, vintage profiles, and limited editions from the cellar.",
    },
    {
        "slug": "vineyard",
        "label": "Vineyard",
        "blurb": "Harvest reports, terroir, and life among the vines.",
    },
    {
        "slug": "entertaining",
        "label": "Entertaining",
        "blurb": "Pairings, gifts, and occasions to share a bottle.",
    },
    {
        "slug": "knowledge",
        "label": "Knowledge",
        "blurb": "Guides, education, and a deeper read on English sparkling.",
    },
    {
        "slug": "experiences",
        "label": "Experiences",
        "blurb": "Tours, tastings, and the table at the estate.",
    },
    {
        "slug": "sustainability",
        "label": "Sustainability",
        "blurb": "Our B Corp journey, charity partners, and the long view.",
    },
    {
        "slug": "estate-life",
        "label": "Estate Life",
        "blurb": "The people, heritage, and stories behind Ridgeview.",
    },
]


def clean_html(s):
    """Strip HTML + decode entities + collapse whitespace. For excerpts only."""
    if not s:
        return ""
    s = re.sub(r"<[^>]+>", "", s)
    s = unescape(s)
    s = re.sub(r"\s+", " ", s).strip()
    # WordPress sometimes appends " [&hellip;]" → remove
    s = re.sub(r"\[\s*&hellip;\s*\]\s*$", "", s)
    s = re.sub(r"\[\s*…\s*\]\s*$", "", s)
    s = re.sub(r"…\s*$", "", s).strip()
    return s


def clean_title(s):
    return clean_html(s)


def find_hero(slug):
    """Find the on-disk hero image, return /-relative path or None."""
    d = HERO_DIR / slug
    if not d.exists():
        return None
    for name in ("hero.webp", "hero.jpg", "hero.jpeg", "hero.png"):
        f = d / name
        if f.exists():
            size_kb = f.stat().st_size // 1024
            return f"/images/articles/{slug}/{name}", size_kb
    return None, 0


def to_ts_string(s):
    """Escape a Python string for a TypeScript double-quoted literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    meta = {p["id"]: p for p in json.loads(METADATA.read_text())}
    cats = json.loads(CATEGORIZED.read_text())

    articles = []
    placeholders = []

    for cat_entry in cats:
        post = meta[cat_entry["id"]]
        slug = cat_entry["slug"]
        title = clean_title(post["title"]["rendered"])
        excerpt = clean_html(post.get("excerpt", {}).get("rendered", ""))
        date = post["date"][:10]
        category = cat_entry["category"]

        hero = find_hero(slug)
        if hero:
            hero_path, size_kb = hero
            if size_kb < 15:
                placeholders.append(slug)
        else:
            hero_path = ""

        articles.append({
            "slug": slug,
            "category": category,
            "title": title,
            "date": date,
            "excerpt": excerpt,
            "heroImage": hero_path,
        })

    if placeholders:
        PLACEHOLDER_SLUGS_FILE.write_text("\n".join(placeholders) + "\n")
        print(f"Wrote {len(placeholders)} placeholder-hero slugs to "
              f"{PLACEHOLDER_SLUGS_FILE.name}")

    # Sort articles newest first
    articles.sort(key=lambda a: a["date"], reverse=True)

    # ── Emit the TS file ────────────────────────────────────────────────
    lines = []
    push = lines.append

    push('// AUTO-GENERATED by tools/generate_articles_ts.py')
    push('// Phase 2: metadata + hero images only. Bodies populated in Phase 3.')
    push('// Do not edit by hand — re-run the generator instead.')
    push('')
    push('export type CategorySlug =')
    push('  | "wines"')
    push('  | "vineyard"')
    push('  | "entertaining"')
    push('  | "knowledge"')
    push('  | "experiences"')
    push('  | "sustainability"')
    push('  | "estate-life";')
    push('')
    push('export interface CategoryMeta {')
    push('  slug: CategorySlug;')
    push('  label: string;')
    push('  blurb: string;')
    push('  /** Computed at render time from the articles[] list. */')
    push('  count?: number;')
    push('  /** Representative hero image for the homepage card. */')
    push('  image: string;')
    push('}')
    push('')
    push('export type ArticleBlock =')
    push('  | { type: "paragraph"; text: string }')
    push('  | { type: "heading"; level: 2 | 3; text: string }')
    push('  | { type: "image"; src: string; alt: string; caption?: string }')
    push('  | { type: "quote"; text: string; attribution?: string }')
    push('  | { type: "list"; ordered: boolean; items: string[] };')
    push('')
    push('export interface Article {')
    push('  slug: string;')
    push('  category: CategorySlug;')
    push('  title: string;')
    push('  date: string;        // YYYY-MM-DD')
    push('  excerpt: string;')
    push('  heroImage: string;   // /images/articles/<slug>/hero.<ext>')
    push('  /** Filled in Phase 3. */')
    push('  body?: ArticleBlock[];')
    push('}')
    push('')

    # Pick a representative hero per category (newest article in that cat
    # that has a non-placeholder hero)
    cat_images = {}
    for cm in CATEGORY_META:
        cat_slug = cm["slug"]
        cat_articles = [a for a in articles if a["category"] == cat_slug and a["heroImage"]]
        # prefer non-placeholder
        good = [a for a in cat_articles if a["slug"] not in placeholders]
        pick = (good or cat_articles or [{}])[0]
        cat_images[cat_slug] = pick.get("heroImage", "")

    push('export const categories: CategoryMeta[] = [')
    for cm in CATEGORY_META:
        push("  {")
        push(f'    slug: "{cm["slug"]}",')
        push(f'    label: "{to_ts_string(cm["label"])}",')
        push(f'    blurb: "{to_ts_string(cm["blurb"])}",')
        push(f'    image: "{cat_images[cm["slug"]]}",')
        push("  },")
    push('];')
    push('')

    push('export const articles: Article[] = [')
    for a in articles:
        push("  {")
        push(f'    slug: "{a["slug"]}",')
        push(f'    category: "{a["category"]}",')
        push(f'    title: "{to_ts_string(a["title"])}",')
        push(f'    date: "{a["date"]}",')
        push(f'    excerpt: "{to_ts_string(a["excerpt"])}",')
        push(f'    heroImage: "{a["heroImage"]}",')
        push("  },")
    push('];')
    push('')

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} — {len(articles)} articles, {len(CATEGORY_META)} categories")

    # Print distribution
    from collections import Counter
    dist = Counter(a["category"] for a in articles)
    print("\nDistribution:")
    for cm in CATEGORY_META:
        print(f"  {cm['slug']:18s} {dist[cm['slug']]:3d}")


if __name__ == "__main__":
    main()
